<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <description>这个项目就是自己纯手搓的了</description>

<!-- 这个是我当前项目的GAV坐标(类似于Maven项目中的身份证) 别人依赖我这个项目时就会用到我的GAV-->
    <groupId>com.yihua</groupId> <!--公司/组织名 -->
    <artifactId>BOM_Demo</artifactId> <!--项目名-->
    <version>1.0-fairyCat-SNAPSHOT</version><!--版本号 SNAPSHOT表示随时可能会变的快照版本 SNAPSHOT必须全大写-->

    <packaging>jar</packaging> <!-- 打包的时候打jar包后面就可以用java -jar命令直接跑起来喵~ -->

<!--parent标签作用: 继承"父项目"的配置，避免重复写。-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/> <!--没写值代表会去远程仓库中下载-->
    </parent>

<!--
        定义一些属性变量
        如果是第三方的依赖就必须得指定版本 父项目中是没有这些工具的 不指定就会报错的
        像组织是org.springframework.boot就是父项目中有的依赖
-->
    <properties>
        <java.version>8</java.version>
        <mybatis-plus-version>3.5.5</mybatis-plus-version>
        <mysql.version>8.0.33</mysql.version>
    </properties>

<!-- 引用一些相关的依赖包进来  或者说引入一些其它的项目进来复用。-->
<!--    这里不需要指定对应的版本 应为已经继承了父项目中的版本号了-->
    <dependencies>

<!--        写接口的注解、返回JSON的注解、所要用到的web场景启动器 -->
<!--        这里需要注意返回对象的时候要想被@RestController注解转成JSON 需要对象有getXXX方法 -->
        <!-- 这里有一个好用的工具： org.springframework.beans.BeanUtils  -->
        <!-- 里面有一个方法： copyProperties(A,B) 可以把A中同名的属性赋值给B中同名的属性  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

<!--        参数校验的场景启动器-->
<!--        里面的一些注解可以代替人为的if判断校验 比如常用的就是@NotBlank 不为NULL或空字符串-->
<!--        配合在实体类上的注解与接收对象前的注解@Valid来实现参数校验-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

<!--        这个包主要提供@Data注解  通过它可以自动生成对应的get/set方法、并重写toString、hashCode、equals等方法-->
<!--        这里面还有个好玩的注解： @Builder 可以达到建造者的效果 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional> <!--其它成员引用本项目时候不会自动导入当前的这个lombok包 防止依赖污染 -->
        </dependency>

<!--        引用绑定表与实体类的一些注解 比如 @TableId @TableName @TableField这些-->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis-plus-version}</version>
        </dependency>

<!--
        引入连接mysql数据库的依赖  之后直接去配置文件中配置连接信息就可以使用了
        如果只引用了连接依赖包 但没有配置数据源信息就会报错
-->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mysql.version}</version>
            <scope>runtime</scope> <!--项目跑起来的时候需要这个包 在写代码的时候不需要-->
        </dependency>

<!--        引入测试工具的场景启动器 后面可以使用相关的注解 比如@SpringBootTest 跟@Test来进行单元测试-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope> <!-- 只需要在测试的时候用 在编译跟打包的时候不用 -->
        </dependency>

    </dependencies>

<!--    使用<distributionManagement>标签将当前项目对应的jar包上传到私服Nexus中去-->
<!--    distributionManagement翻译过来就是分发管理的意思 它告诉Maven当执行mvn deploy命令的时候应该把打好的jar包上传到哪个地方-->
<!--    这里配置好后还需要到Maven的配置文件settings.xml中再配置一下 位置行号： 135-->
<!--    Maven会根据当前项目<Version>标签中包不包含SNAPSHOT来判断应该放到下面的哪个私有仓库中去-->
<!--    如果包含SNAPSHOT(代表随时会变的快照版本，允许重复覆盖上传)，则会上传到下面的快照仓库snapshotRepository中-->
<!--    如果不包含SNAPSHOT(最终发布版本，一旦上传就不允许再覆盖了)，则会上传到下面的正式版本repository中-->

<!--    注意在Maven的日常维护中 只需要使用生命周期中的命令就可以了 插件中的命令是给高级用户提供的-->
<!--    它们之间的关系就是 生命周期是一个接口 而插件中的命令是具体的实现类 -->
<!--    调用这个接口的时候它会自动去找合适的那个实现类 而如果自己是直接单独调用的插件中的命令很容易报错 -->
<!--    所以下次部署上去先去Maven中的生命周期中执行以下命令： clean->compile->package->deploy就好了-->
    <distributionManagement>

<!--        快照仓库-->
        <snapshotRepository>
<!--            id标签是仓库的唯一标识，要跟settings.xml配置中server标签里面的id对应上(用于登录认证)-->
            <id>nexus-snapshots-fairyCat</id>
<!--            name标签主要是一个描述 给人看的 不影响功能-->
            <name>存放当前项目的快照版本</name>
<!--            url标签主要对应着仓库的实际HTTP访问地址-->
            <url>http://localhost:8088/repository/maven-snapshots/</url>
        </snapshotRepository>

<!--        正式仓库-->
        <repository>
            <id>nexus-releases-fairyCat</id>
            <name>存放项目的所有正式版本</name>
            <url>http://localhost:8088/repository/maven-releases/</url>
        </repository>
<!--        这样别人在pom.xml中引入我项目的GAV坐标后再执行mvn install命令的时候它就会去私服上面下载我上传的jar包了-->
<!--        而我执行mvn deploy命令就会把当前项目的jar包上传到本地Nexus私服中去-->
    </distributionManagement>

<!--    使用repositories标签从Nexus远程仓库中下载对应的依赖-->
<!--    <repositories>标签告诉Maven从哪里下载别人的依赖-->

    <!--配置Nexus远程仓库 后面Maven在下载依赖的时候会自动去Nexus远程仓库中找-->
    <repositories>
            <repository>
<!--            <id>标签里面的值是唯一的，但名称可自定义，尽量命名的语义清晰一点
                它主要是一个登录凭证的key Maven会通过这个key去settings.xml文件中找这个key对应的value(对应的用户名跟密码) 也就是在<server>标签的位置-->
<!--            上传jar的时候是需要凭证的 所以需要指定Nexus对应的用户名跟密码-->
<!--            但下载的时候一般是不需要的 Nexus是允许匿名访问的 所以这里的id也可以不用去Settings.xml中配置server对应的用户名跟密码
                但如果管理员取消勾选了允许匿名访问的话 那就必须得认证了 这个时候就得去Settings.xml中配置server，配置对应的用户名跟密码了 -->
                <id>downloadAllRepositoryFromRepositoryGroup</id>
<!--            <name>标签 用于描述给人看的文字内容-->
                <name>Nexus的仓库组，里面有所有仓库对应的依赖，比如代理仓库、宿主仓库等</name>
<!--            <url>标签表示下载地址 从哪里下载对应的依赖
                这里设置的是仓库组的地址
                仓库组里面不会存依赖(数据)，它就像是一个前台，如果别人来仓库组拉依赖的话
                仓库组它会去它下面的所有仓库成员(默认会添加快照、正式、代理中央仓库这些成员)找一遍，直到找到那个依赖，如果没有的话才会通过代理仓库去中央仓库找
                所以这里并不需要担心配置的是仓库组的URL后以为仓库组中没有依赖别人就拉取不到自己上传到快照版或正式版中的jar了
                如果在settings.xml文件中配置了镜像mirror  则Maven所有对中央仓库的请求都会被拦截到来访问那个镜像所在的地址
                如果在拉取私服Nexus里面的依赖失败了 可以把http换成https试一下
                因为从Maven3.8.1开始 官方出于安全考虑(防止有人在中途篡改依赖里面的代码) 默认会禁止从非localhost的http请求所在的外部仓库中下载相应的依赖 然后重定向到这个地址:0.0.0.0
                -->
                <url>http://localhost:8088/repository/maven-public/</url>
<!--            release标签跟snapshots标签对应着正式版与快照版  这里配合enabled标签就相当于一个控制别人能否从这两个仓库下载的一个开关
                下面这两个版本的仓库对应的enabled都是true 则表示当前项目是能从它们那里下载对应的依赖的-->
                <releases>
<!--                <enabled>标签如果是true则表示允许从Nexus里面拉取对应的依赖 如果是false的话则表示就算Nexus远程仓库中有这个依赖 但也不允许拉取下来-->
                    <enabled>true</enabled>
                </releases>
                <snapshots>
                    <enabled>true</enabled>
                    <!-- <updatePolicy>标签的作用: 当执行mvn构建命令解析依赖时且本地已有缓存的情况下 要不要再去远程仓库确认一下有没有最新版本，如果有的话就拉取下来，覆盖掉原来的旧版本，控制的是多久确认一次的频率
                     参数： always: 每次构建时都会去远程仓库检查一遍(间隔时间0秒)
                     daily: 默认值，不写就这个，隔24小时后才会检查一遍 如果当前距离上次在远程仓库检查的时间点没超过24小时 则在构建的时候不会去远程仓库上找最新版本
                     interval: 30  表示距上次检查时间点相隔30分钟后才会检查一次
                     never: 从不检查，这样就会一直用快照原来的旧版本 如果出现同一版本 但里面的版本内容不同 不主动去远程仓库上拉取最新版本内容的话出了Bug去查的时候还是查的原来旧版本逻辑-->
<!--                 这里可以使用mvn -U clean package命令强制重置时间间隔直接从远程仓库中拉取最新的依赖 -U就是强制刷新的意思
                    注意拉取依赖是打包过程中自动执行的一个内置步骤 所以直接执行上面这行命令就完事了
                    最重要的一点就是需要将当前项目的Maven配置成本地的Maven才行 不然的话下载依赖就会出Bug的-->
                    <updatePolicy>always</updatePolicy>
                </snapshots>
            </repository>
    </repositories>

    <build>
        <plugins>

<!--            Maven的打包插件，将当前项目、相关依赖、内置的Tomcat全都打成一个可以直接用java -jar命令运行的jar包
                这个插件好像没有2.7.10版本 下载依赖的时候报错了
-->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
<!--                <configuration> 标签告诉Maven插件要按照我设置的规则来-->
                <configuration>
                    <excludes>
<!--                        lombok的相关依赖包不需要打进jar包里 因为在编译的时候它的相关注解已经完成了它的使命-->
<!--                        后面就不再需要lombok中的相关注解了 所以可以不打进jar包里以节省空间-->
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>